# Generated by Django 2.2.4 on 2019-09-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
